<%@ page import="edu.mcw.rgd.process.mapping.MapManager" %>
<style>
    .snpMenuBar {
        background-color:#F0F6F9;
        border: #771428;
        background-image: url(/rgdweb/common/images/bg3.png);
        padding: 12px 15px;
    }
</style>

<style type="text/css">
.classname {
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
	box-shadow:inset 0px 1px 0px 0px #ffffff;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
	background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
	background-color:#ededed;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #dcdcdc;
	display:inline-block;
	color:#073c6a;
	font-family:arial;
    z-index:1;
	font-size:13px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #ffffff;
}.classname:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
	background-color:#dfdfdf;
}.classname:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>

<%
    HttpRequestFacade req2 = new HttpRequestFacade(request);

    String uri = request.getRequestURL().substring(request.getRequestURL().lastIndexOf("/")+1);

    boolean functionSearch = false;
    boolean geneSearch=false;
    boolean positionSearch=false;
    boolean resultsRendered = false;
    List<Integer> sampleList=(List<Integer>)request.getAttribute("sampleIds");
    geneList=req2.getParameter("geneList").replaceAll("\\s",",");

    if (!req2.getParameter("rdo_acc_id").equals("") || !req2.getParameter("pw_acc_id").equals("") ||
            !req2.getParameter("chebi_acc_id").equals("") || !req2.getParameter("mp_acc_id").equals("") ) {

            functionSearch=true;

    }else if (!req2.getParameter("geneList").equals("")) {
        geneSearch=true;
    }
    else if (!req2.getParameter("start").equals("") || !req2.getParameter("geneStart").equals("")){
        positionSearch=true;
    }

    if (uri.contains("variants") || uri.contains("dist")) {
        resultsRendered= true;
    }
    String parameters=request.getQueryString();
    if( parameters==null ){
        StringBuffer sb=new StringBuffer();
        sb.append("chr=");
        sb.append(req.getParameter("chr"));
        sb.append("&mapKey=");
        sb.append(req.getParameter("mapKey"));
        sb.append("&start=");
        sb.append(req.getParameter("start"));
        sb.append("&stop=");
        sb.append(req.getParameter("stop"));
        if( sampleList!=null ) {
            int i = 1;
            for (int id : sampleList) {
                sb.append("&sample" + i + "=");
                sb.append(id);
                i = i + 1;
            }
        }
        parameters=sb.toString();
    }

    String selectTitle="Edit&nbsp;Strains";
    int map= 0;
    try {
        map = MapManager.getInstance().getReferenceAssembly(3,"NCBI").getKey();
    } catch (Exception e) {
        e.printStackTrace();
    }
    if(req2.getParameter("mapKey")!=null && !req2.getParameter("mapKey").equals("")) {
        try {
            map = Integer.parseInt(req2.getParameter("mapKey"));
        }catch (Exception ignored){}
    }
    // if (MapManager.getInstance().getMap(mapKey).getSpeciesTypeKey() == 1) {
    if (map==37 || map==38 || map==17) {
        selectTitle="Edit&nbsp;Sequences";
    }
    if (map==631) {
        selectTitle="Edit&nbsp;Breeds";
    }

%>
<div class="snpMenuBarOuterBorder" >

    <table id="headerBar"  class="snpMenuBar">
    <tr>
        <td align="left" width="10%">
            <table cellpadding=0 cellspacing=0  >
            <tr>
                <td>&nbsp;</td>
                <td><a href="config.html" class="classname">Home</a></td>
                <td>&nbsp;&nbsp;&nbsp;</td>
                <td><a href="select.html?<%=parameters%>" class="classname"><%=selectTitle%></a></td>

                    <% if (positionSearch) { %>
                        <td>&nbsp;&nbsp;&nbsp;</td>
                        <td><a href="region.html?<%=parameters%>" class="classname">Region</a></td>
                    <% } %>

                     <% if (geneSearch) { %>
                          <td>&nbsp;&nbsp;&nbsp;</td>
                          <td><a  href="geneList.html?<%=parameters%>" class="classname">Edit&nbsp;Gene&nbsp;List</a></td>
                     <% } %>


                    <% if (functionSearch) { %>
                        <td>&nbsp;&nbsp;&nbsp;</td>
                        <td><a  href="annotation.html?<%=parameters%>" class="classname">Functional&nbsp;Annotation</a></td>
                    <% } %>

                    <% if (resultsRendered) { %>
                        <td>&nbsp;&nbsp;&nbsp;</td>
                        <td><a href="options.html?<%=parameters%>" class="classname">Sequence&nbsp;Annotation</a></td>
                    <% }%>
            </tr>
            </table>

        </td>

        <td style="color: white; font-size:16px; padding-left: 30px;">
            <% if (request.getParameter("mapKey") != null && !request.getParameter("mapKey").equals("")) { %>

            Assembly

            <%
                try {%>
            <%=MapManager.getInstance().getMap(map).getName()%>

           <% } catch (Exception e) {
            } } %>
        </td>
        <td align="right" width="10%">
            <div id="appMenu">
            <table>
                <tr>
                    <td>
                        <div  style="width:25px;">
                            <div id="appBar1" style="background-color:white; height:3px; width:30px;"></div>
                            <div style="height:3px; width:25px;"></div>
                            <div id="appBar2"style="background-color:white; height:3px; width:30px;"></div>
                            <div style="height:3px; width:25px;"></div>
                            <div id="appBar3"style="background-color:white; height:3px; width:30px;"></div>
                            <div style="height:3px; width:25px;"></div>
                        </div>

                    </td>
                    <!--
                    <td>
                        <div style="font-size:16px; vertical-align:center; height:18px; color:white; float:right;">Menu</div>
                    </td>
                    -->
                    <td>&nbsp;&nbsp;&nbsp;</td>
                </tr>
            </table>
            </div>

        </td>

    </tr>
</table>
</div>
<div id="apps" style="z-index:5000; display:none; position:absolute; top:25; left:50; background-color:white; border: 2px ridge black;">
    <table border=0 cellpadding="5">
        <tr><td align="right" colspan=2 style="background-color:#771428;"><a href="javascript:hideApps(); void(0);"><img src="/rgdweb/js/windowfiles/close.gif" height=20 width=20 border=0/></a> </td></tr>


            <%
            if (request.getRequestURL().indexOf("variants") > 0) {
            %>
            <tr>
                    <td>Display an overview plot of the entire region.  Useful if the region is too large to view on one screen</td>
                    <td><a href="javascript:hideApps(); showOverview();"  class="classname" style="width:200px; text-align: center;">Variant Overview Plot</a></td>
            </tr>
            <tr>
                    <td>The variant distribution feature will display total counts for all genes and intergenic regions.</td>

                    <td><a href="dist.html?<%=request.getQueryString()%>"  class="classname" style="width:200px; text-align: center;">Variant Distribution Graph</a></td>
            </tr>
            <% } %>

            <% if (request.getRequestURL().indexOf("variants") > 0 || request.getRequestURL().indexOf("dist") > 0) {    %>
            <tr>
                    <td>GA Tool:  All genes in the current region will be annotated by the Gene Annotater (GA Tool).</td>
                    <td>
                        <a  style="width:200px; text-align: center;" class="classname" href="/rgdweb/ga/ui.html?o=D&o=W&o=N&o=P&o=C&o=F&o=E&x=19&x=25&x=30&x=45&x=29&x=44&x=20&x=23&x=32&x=27&x=17&x=2&x=42&x=41&x=9&x=3&x=5&x=28&x=12&x=13&x=8&x=1&x=10&x=35&x=7&x=6&x=38&x=39&x=34&x=15&x=18&x=36&x=37&x=21&x=31&x=43&x=24&x=33&x=26&x=22&x=46&x=4&x=40&x=14&ortholog=1&ortholog=2&species=${speciesTypeKey}&chr=1&start&genes=${geneListStr}&mapKey=${mapKey}">
                            Annotate This Region</a></td>
            </tr>
            <tr>
                    <td>Download this graph to Excel or a text file</td>
                    <td><a href="download.html?<%=request.getQueryString()%>"  class="classname" style="width:200px; text-align: center;">Download Data</a></td>
            </tr>
            <% } %>


            <tr>
                <td>Variant Visualizer Help Documentation</td>
                <td style="font-style: italic;font-weight:700;"><a href="/rgdweb/variantVisualizer/help.jsp"  class="classname" style="width:200px; text-align: center;">Help Docs</a>&nbsp;&nbsp;&nbsp;&nbsp;</td>
            </tr>
    </table>
</div>

<script>
    function getWidth(){
       return window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth||0;
    }
    function getHeight(){
       return window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight||0;
    }

    function hideApps() {
       document.getElementById('apps').style.display='none';
    }
    function showApps(e) {

        document.getElementById("apps").style.left=getWidth() - 1000;
        document.getElementById("apps").style.display="block";
    }

    function highlightAppSymbol() {
        document.getElementById("appBar1").style.backgroundColor="yellow";
        document.getElementById("appBar2").style.backgroundColor="yellow";
        document.getElementById("appBar3").style.backgroundColor="yellow";
    }
    function lowLightAppSymbol() {
        document.getElementById("appBar1").style.backgroundColor="white";
        document.getElementById("appBar2").style.backgroundColor="white";
        document.getElementById("appBar3").style.backgroundColor="white";
    }

    document.getElementById("appMenu").onclick=showApps;
    document.getElementById("appMenu").onmouseover=highlightAppSymbol;
    document.getElementById("appMenu").onmouseout=lowLightAppSymbol;

</script>

<%
if (request.getAttribute("error") != null ) {
    ArrayList errors = (ArrayList) request.getAttribute("error");
    if( !errors.isEmpty() ) {
%>
    <br><div style="color:red;"><% for( Object o: errors ) { if(o!=null){%>Error: <%=o.toString()%><br><% } }%></div>
<% }} %>
