<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
</head>
<body>
<style>
    p,
    ul,
     li {
        font-size: 13px !important;
        line-height: 1.5 !important;
    }
</style>
<hr>
<div id="dataDownloads" class="subTitle"><span style="display:none">Data Downloads</span><h2>Available Data Downloads</h2></div>
<p>
    Additional data as generated by the HPC RGD RNAseq workflows are available to download at
    our <a href="https://download.rgd.mcw.edu/expression/<%=obj.getGeoSeriesAcc()%>" target="_blank">download site</a>.
</p>
<p>
    Data in downloadable files were aligned to RefSeq genome assembly
    GRCr8 with annotations derived from RefSeq annotation release GCF_036323735.1.
</p>
<p>
    <strong>Available Downloads:</strong>
</p>
<ul>
    <li>A comprehensive html quality report generated with multiqc v1.18</li>
    <li>Gene-level TPM matrix</li>
    <li>Transcript-level TPM matrix</li>
    <li>Gene-level count matrix</li>
    <li>Transcript-level count matrix</li>
    <li>JBrowse2 Genome browser session files. Sessions can be loaded directly into JBrowse2
        for interactive exploration, or individual BigWig files can be downloaded for use in other
        genome browsers.
        <ul>
            <li>Instructions for loading the JBrowse2 session are provided in an accompanying
                JBrowse2_README file. A video tutorial will be available soon on our
                <a href="https://rgd.mcw.edu/wg/home/rgd_rat_community_videos/" target="_blank">RGD Video Tutorials</a> page.</li>
        </ul>
    </li>
</ul>
</body>
</html>
