<%--
  Created by IntelliJ IDEA.
  User: akundurthi
  Date: 11/24/2025
  Time: 12:16 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
</head>
<body>
<style>
    p,
    ul,
     li {
        font-size: 13px !important;
        line-height: 1.5 !important;
    }
</style>
<hr>
<div id="dataProcessing" class="subTitle"><h2>Data Processing</h2></div>
<p>
  <strong>Methods Summary:</strong><br>
Data were processed with the RGD workflow (<a href="https://github.com/rat-genome-database/RGD_RNAseq_workflows" target="_blank">GitHub</a>). Fastq files were downloaded from the Sequence Read Archive and transformed with the sratookit v3.1.1. Quality metrics are generated with FastQC and FastQ-Screen. Upon read quality review and species verification, fastq files are aligned to genome assembly mRatBN7.2 using STAR version=2.7.10b_alpha_220111. STAR alignment files are submitted to RSEM v1.3.1 for expression quantification and output as TPM and counts matrixes. RefSeq annotation release GCF_015227675.2 was used for gene and transcript annotation. Computed Sex infers the sex of a sample based on the ratio of the coverage of the X and Y chromosomes and the expression values of common sex specific genes. A comprehensive QC report is generated with multiqc v1.18.
</p>
<p>
  <strong>**Disclaimer**</strong><br>
  Studies submitted to GEO represent a variety of experimental methods, library preparation methods, and processing softwares and algorithms. The HPC RGD workflow is currently limited to transcriptomic studies run on the illumina sequencing platform, with minimal checks on quality. Therefore, the user must be aware of the following limitations to the provided data:
  <ul>
  <li>
    The data generated by the HPC RGD workflow may not match the published data due to the variety of data processing methods (software, analysis settings, read trimming, etc.) applied by the submitters to generate the data for publication. Users are encouraged to view the original data by navigating to the GEO accession display tool and viewing the processed data files supplied to GEO by the submitter.
  </li>
  <li>
    All TPM data presented for expression studies by RGD have been processed by the same pipeline, RGD does not attempt to correct for any potential bias or confounding factors.
  </li>
  <li>
    A study may be missing values for one or many samples. This could be a result of technical reasons such as corrupted or missing raw read files or low genome assembly alignment rates. Samples with less than a 50% STAR alignment rate to mRatBN7.2 will not be processed with RSEM to generate abundance estimates.
  </li>
  <li>
    A study may be missing values for one or many genes in the database gene expression table display, RGD does not store TPM values equal to 0. All genes used in the alignment process are output in the matrix files provided in the downloads directory.
  </li>
  <li>
    Computed sample sex may disagree with sex submitted to GEO. Sex estimates are based on x:y coverage ratio and expression of limited list of sex specific genes. Coverage and expression values may be impacted for a variety of technical factors. Where there are significant discrepancies at the study level, RGD curators reach out to data submitters for further clarification.
  </li>
</ul>
</p>
</body>
</html>
