<%--
  Created by IntelliJ IDEA.
  User: akundurthi
  Date: 11/24/2025
  Time: 12:16 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
</head>
<body>
<style>
    p,
    ul,
     li {
        font-size: 13px !important;
        line-height: 1.5 !important;
    }
</style>
<hr>
<div id="dataProcessing" class="subTitle"><h2>Data Processing</h2></div>
<p>
  <strong>**Disclaimer**</strong><br>
  Studies submitted to GEO represent a variety of experimental methods, library preparation methods,  and processing software and algorithms. The HPC RGD workflow is currently limited to transcriptomic studies run on the illumina sequencing platform, within minimal checks on quality. Therefore, the user must be aware of the following limitations to the provided data:
  <ul>
  <li>
    The data generated by the HPC RGD workflow may not match the published data due to the variety of data processing methods (software, analysis settings, etc.) applied by the submitters to generate the data for publication. Users are encouraged to view the original data by  navigating to the GEO accession display tool and viewing the processed data files supplied to GEO by the submitter.
  </li>
  <li>
    Although all TPM data presented for expression studies by RGD have been processed by the same pipeline, RGD does not attempt to correct for any potential bias or confounding factors. For more information regarding considerations in making quantitative comparisons across samples <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7373998/" target="_blank">this article by Zhao et. al</a> is a good resource.
  </li>
  <li>
    A study may be missing values for one or many samples, the reason being failure due to a technical reason such as corrupted or missing raw read files or low genome assembly alignment rates.
  </li>
  <li>
    A study may be missing values for one or many genes, RGD does not store TPM values = to 0.
  </li>
  <li>
    Computed sample sex may disagree with sex submitted to GEO. Sex estimates are based on x:y coverage ratio and expression of limited list of sex specific genes. Coverage and expression values may be impacted for a variety of reasons such as experiment conditions, animal life stage, or other technical factors.
  </li>
</ul>
</p>
<p>
  <strong>Methods Summary:</strong><br>
Data were processed with the RGD workflow. Fastq files were downloaded from the Sequence Read Archive and transformed with the <a href="https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit#ncbi-sra-toolkit" target="_blank">sratookit v3.1.1</a>. Quality metrics are generated with <a href="https://www.bioinformatics.babraham.ac.uk/projects/fastqc/" target="_blank">FastQC</a> and <a href="https://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/" target="_blank">FastQ-Screen</a>. Upon read quality review and species verification, fastq files are aligned to genome assembly mRatBN7.2 using <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC3530905/" target="_blank">STAR</a> version=2.7.10b_alpha_220111. STAR alignment files are submitted to <a href="https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-12-323" target="_blank">RSEM v1.3.1</a> for expression quantification and output as a TPM matrix. Annotation release GCF_015227675.2 was used for gene and transcript annotation. Computed Sex infers the sex of a sample based on the ratio of the coverage of the X and Y chromosomes and the expression values of common sex specific genes. A comprehensive QC report is generated with <a href="https://seqera.io/multiqc/" target="_blank">multiqc v1.18</a> and available for  download for sample QC metrics.
</p>
</body>
</html>
