        <p ><a href="https://www.toxicology.org/events/am/AM2019/registration.asp" target="_blank" rel="noopener">58th Annual Meeting of the Society of Toxicology &amp; ToxExpo, Baltimore Convention Center, Baltimore, MD, USA &#8211; March 10-14, 2019</a></p>
        <p><a href="https://10times.com/experimental-biology-orlando" target="_blank" rel="noopener">Experimental Biology 2019, Rosen Centre Hotel, Orlando, FL, USA, April 6-10, 2019</a></p>
        <p ><a href="https://www.biocuration2019.org/" target="_blank" rel="noopener">Biocuration 2019, The 12th International Biocuration Conference, West Road Concert Hall, Cambridge, UK &#8211; April 7-10, 2019</a></p>
        <p ><a href="http://wiki.geneontology.org/index.php/Consortium_Meetings_and_Workshops#2019" target="_blank" rel="noopener">Gene Ontology Consortium Meeting, Cambridge, UK, April 11-13, 2019</a></p>
        <p ><a href="https://www.amia.org/cic2019?gclid=CjwKCAiA4t_iBRApEiwAn-vt-3lRwhE34586XKVO3-7YblkFfpsJpEV_eUG4hP493lsCQ6mOd5Wv_BoCggUQAvD_BwE" target="_blank" rel="noopener">AMIA 2019 Clinical Informatics Conference, W Atlanta Midtown Hotel, Atlanta, GA, USA &#8211; April 30-May 2, 2019</a></p>
        <p ><a href="https://meetings.cshl.edu/meetings.aspx?meet=GENOME&amp;year=19" target="_blank" rel="noopener">The Biology of Genomes, Cold Spring Harbor, NY, USA &#8211; May 7-11, 2019; Abstract deadline: February 15, 2019</a></p>
        <p ><a href="https://ibangs.memberclicks.net/assets/media/IBANGS%202019%20.png" target="_blank" rel="noopener">21st International Behavioural and Neural Genetics Society (IBANGS) Meeting, University of Edinburgh, Edinburgh, Scotland, May 10-14, 2019</a></p>
        <p ><a href="https://www.iscb.org/glbio2019" target="_blank" rel="noopener">Great Lakes Bioinformatics Conference, Union South building, UW Madison, Madison, WI, USA &#8211; May 19-22, 2019; Abstract deadline (oral presentations): March 11, 2019</a></p>
        <p ><a href="https://meetings.cshl.edu/meetings.aspx?meet=SYMP&amp;year=19" target="_blank" rel="noopener">84th Symposium: RNA Control &amp; Regulation, Cold Spring Harbor, NY, USA &#8211; May 29-June 3, 2019; Abstract deadline: March 8, 2019</a></p>
        <p ><a href="http://ratgenes.org/ctc2019/" target="_blank" rel="noopener">17th Annual Meeting of the Complex Traits Consortium/Rat Genomics, Medical Education and Telemedicine building, UCSD, La Jolla, CA, USA &#8211; June 8-11, 2019</a></p>
        <p ><a href="https://meetings.cshl.edu/meetings.aspx?meet=BIOME&amp;year=19" target="_blank" rel="noopener">Microbiome, Cold Spring Harbor, NY, USA &#8211; July 18-21, 2019; Abstract deadline: May 3, 2019</a></p>
        <p ><a href="https://www.iscb.org/ismbeccb2019" target="_blank" rel="noopener">27th Conference on Intelligent Systems for Molecular Biology/18th European Conference on Computational Biology, Congress Center Basel, Basel, Switzerland &#8211; July 21-25, 2019; Abstract deadline: April 11, 2019</a></p>
        <p ><a href="https://sites.google.com/view/icbo2019" target="_blank" rel="noopener">10th International Conference on Biomedical Ontology, Buffalo, NY, USA &#8211; July 29-August 2, 2019; Abstract deadline: May 15, 2019</a></p>
        <p ><a href="https://www.amia.org/amia2019" target="_blank" rel="noopener">AMIA 2019 Annual Symposium, Washington, DC, USA &#8211; November 16-20, 2019; Submission deadline: March 13, 2019</a></p>
